- .github/workflows/github-actions-demo.yml
- .github/workflows/lint-and-format.yml
- backend/src/app.service.ts
- backend/src/main.ts
> github actions

- .vscode/settings.json
> VS Code拡張機能エラー対応

- Makefile
#12  の対応
なんか動きがおかしい時は、
`make clean && make init`すれば治る（ときもあるかも？）
> Makefile clean ルール

- backend/src/Chat/chat.gateway.spec.ts
- backend/src/Chat/chat.gateway.ts
- backend/src/Chat/chat.module.ts
- backend/src/app.module.ts
- backend/src/events/events.module.ts
- frontend/.eslintrc.json
- frontend/.prettierrc
- frontend/src/App.tsx
- frontend/src/Chat/Chat.tsx
- frontend/src/Chat/ChatList.tsx
- frontend/src/Game/Match.tsx
- frontend/src/Login.tsx
- frontend/src/index.tsx
- frontend/src/utils.tsx
- resolve #20 
- Chatモジュールでfrontendのlintエラーが出ているので、対応
> rename event module

- frontend/src/App.tsx
動作確認時に便利なように、mainpageにリンクを設定。
resolve #29
> add link in mainpage

- backend/src/Chat/chat.gateway.ts
- frontend/src/Chat/Chat.tsx
> [チャット]ソケット重複バグ対応

- backend/src/Chat/chat.gateway.ts
- frontend/src/Chat/Chat.tsx
- frontend/src/Chat/ChatList.tsx
> chat room UI

- frontend/src/Chat/Chat.tsx
> remove stringfy

- .vscode/settings.json
> [VSCode]add dictionary

- frontend/src/Game/Match.tsx
closes #40 
もう少し単純な方法があると思いますが機能はしています。
> paddleの角度を調整する機能

- backend/src/chat/chat.gateway.ts
- backend/src/chat/dto/chat.dto.ts
- backend/src/chatRoom/chatRoom.controller.ts
- backend/src/chatRoom/chatRoom.module.ts
- backend/src/chatRoom/chatRoom.service.ts
- backend/src/chatRoom/dto/chatRoom.dto.ts
- backend/src/chatRoom/index.ts
- backend/src/common/app.module.ts
- backend/src/entities/chatMuteUser.entity.ts
- backend/src/entities/chatRoom.entity.ts
- backend/typings/chatRoom.d.ts
- config/.env_frontend
- frontend/src/Chat/components/Chat.tsx
- frontend/src/Chat/components/ChatList.tsx
- frontend/src/Chat/types/ChatList.d.ts
- swagger/api.yml
> chat room backend

- backend/src/chat/chat.gateway.ts
- frontend/src/App.tsx
- frontend/src/Chat/components/Chat.tsx
- frontend/src/Chat/components/ChatList.tsx
- frontend/src/Chat/types/Chat.d.ts
- frontend/src/types/Chat.d.ts
> [Chat]rename kick

- frontend/src/Chat/assets/styles.css
- frontend/src/Chat/components/Chat.tsx
> [チャット]icon

- frontend/src/Chat/components/ChatList.tsx
> [チャット]private room

- backend/src/users/index.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.module.ts
- backend/src/users/users.service.ts
ディレクトリ名を`Users`から`users`に変更しました。
ディレクトリ名の大文字小文字を捕捉させるためには`git config core.ignorecase false`を実行しました。
ファイルの中身は変更していません。
> [fix] Users -> users

- backend/src/chatRoomMembers/chatRoomMembers.controller.ts
- backend/src/chatRoomMembers/chatRoomMembers.module.ts
- backend/src/chatRoomMembers/chatRoomMembers.service.ts
- backend/src/chatRoomMembers/index.ts
- backend/src/common/app.module.ts
- backend/src/common/dto/chatRoomMembers.dto.ts
- swagger/api.yml
resolve #109 
- バックエンドでAPIを作成する。(Get/Post/Delete)
> [チャット]API for chatRoomMembers

- docker-compose.yml
#124 
[参考URL]
https://qiita.com/suin/items/067b7883c038b363b2d7
> fix log level

- backend/migrations/1676466055353-migrations.ts
- backend/src/chatRoom/chatRoom.controller.ts
- backend/src/chatRoom/chatRoom.module.ts
- backend/src/chatRoom/chatRoom.service.ts
- backend/src/common/app.module.ts
- backend/src/common/dto/chatRoom.dto.ts
- backend/src/entities/chatRoom.entity.ts
- frontend/src/Chat/components/ChatList/ChatListDisplay.tsx
- frontend/src/Chat/components/ChatList/ChatListModal.tsx
- frontend/src/Chat/types/ChatList.d.ts
- swagger/api.yml
> [チャット][BUG]chatRoom api

- backend/src/common/app.module.ts
- backend/src/common/dto/users.dto.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
- swagger/api.yml
> [User] 全User情報の取得APi

- backend/src/chatRoomMembers/chatRoomMembers.service.ts
- frontend/src/Chat/components/ChatList/ChatListDisplay.tsx
- frontend/src/Chat/components/ChatList/ChatListModal.tsx
- frontend/src/Chat/components/ChatRoom/AddUserButton.tsx
- frontend/src/Chat/components/ChatRoom/AddUserModal.tsx
- frontend/src/Chat/components/ChatRoom/ChatRoom.tsx
- frontend/src/Chat/components/ChatRoom/UserListDisplay.tsx
- frontend/src/Chat/index.tsx
- frontend/src/Chat/types/ChatList.d.ts
- frontend/src/Chat/types/ChatRoom.d.ts
- frontend/src/index.tsx
- frontend/src/types/Chat.d.ts
resolve #92 
resolve #105
#116 のうち、管理画面の作成のみ対応（実際の処理は未実装）
> [チャット] room setting画面の追加＆一覧画面のアップデート

- backend/src/common/dto/users.dto.ts
- backend/src/common/params/user.params.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
- swagger/api.yml
> [User] Delete, Update

- backend/migrations/1676466055353-migrations.ts
- backend/src/chatRoom/chatRoom.controller.ts
- backend/src/chatRoom/chatRoom.module.ts
- backend/src/chatRoom/chatRoom.service.ts
- backend/src/chatRoomMembers/chatRoomMembers.module.ts
- backend/src/common/dto/chatRoom.dto.ts
- backend/src/entities/chatRoom.entity.ts
- frontend/src/Chat/components/ChatList/ChatListDisplay.tsx
- frontend/src/Chat/components/ChatList/ChatListModal.tsx
- frontend/src/Chat/types/ChatList.d.ts
- swagger/api.yml
> [チャット] protectedルーム(backend)

- backend/src/entities/chatRoomMembers.entity.ts
- frontend/src/Chat/components/ChatRoom/AddUserButton.tsx
- frontend/src/Chat/components/ChatRoom/AddUserModal.tsx
- frontend/src/Chat/components/ChatRoom/ChatRoom.tsx
- frontend/src/Chat/components/ChatRoom/UserListDisplay.tsx
- frontend/src/Chat/components/ChatRoom/requestUtils.tsx
- frontend/src/Chat/types/ChatRoom.d.ts
> [チャット]member add/delete/ban

- backend/src/chatRoomMembers/chatRoomMembers.service.ts
- backend/src/common/dto/chatRoomMembers.dto.ts
- backend/src/entities/chatRoomMembers.entity.ts
- swagger/api.yml
> [チャット]admin backend

- backend/migrations/1676466055353-migrations.ts
> [チャット]migration

- backend/src/chatRoom/chatRoom.controller.ts
- backend/src/chatRoom/chatRoom.service.ts
- backend/src/chatRoomMembers/chatRoomMembers.service.ts
- backend/src/common/dto/chatRoom.dto.ts
- backend/src/common/dto/chatRoomMembers.dto.ts
- backend/src/entities/chatRoom.entity.ts
- backend/src/entities/chatRoomMembers.entity.ts
- frontend/src/Chat/components/ChatList/ChatListDisplay.tsx
- frontend/src/Chat/components/ChatList/ChatListModal.tsx
- frontend/src/Chat/components/ChatRoom/AddUserButton.tsx
- frontend/src/Chat/components/ChatRoom/AddUserModal.tsx
- frontend/src/Chat/components/ChatRoom/AdminButton.tsx
- frontend/src/Chat/components/ChatRoom/BanButton.tsx
- frontend/src/Chat/components/ChatRoom/ChatRoom.tsx
- frontend/src/Chat/components/ChatRoom/MuteButton.tsx
- frontend/src/Chat/components/ChatRoom/UserListDisplay.tsx
- frontend/src/Chat/components/utils/DeleteMemberButton.tsx
- frontend/src/Chat/components/utils/MutedIcon.tsx
- frontend/src/Chat/components/utils/OwnerIcon.tsx
- frontend/src/Chat/components/utils/privateIcon.tsx
- frontend/src/Chat/components/utils/requestUtils.tsx
- frontend/src/Chat/components/utils/userStatusUtils.tsx
- frontend/src/Chat/types/ChatList.d.ts
- frontend/src/Chat/types/ChatRoom.d.ts
- frontend/src/Game/components/Game.tsx
- swagger/api.yml
propsの数を減らして見通しをよくするリファクタリング。
加えて以下のチケットの対応を実施。
resolve #154 
resolve #157 
resolve #153 
resolve #158 
resolve #155 
大規模になってすいません。。
> [チャット]リファクタリング

- .github/workflows/lint-dockerfile.yml
- Makefile
resolve #165 
「Docker imageはlatestではなくバージョンを指定しましょう」という警告を抑止しています。
> Lint Dockerfile

- backend/src/chatRoom/chatRoom.controller.ts
- backend/src/chatRoom/chatRoom.service.ts
- frontend/src/Chat/components/ChatList/EnterButton.tsx
- frontend/src/Chat/types/ChatList.d.ts
- frontend/src/utils/chatRoomAxios.tsx
- swagger/api.yml
> [チャット]URL rename

- frontend/src/Chat/components/ChatList/CreateChatRoomModal.tsx
- frontend/src/Chat/components/ChatRoom/AddUserButton.tsx
- frontend/src/Chat/components/ChatRoom/AddUserModal.tsx
- frontend/src/Chat/components/ChatRoom/AdminButton.tsx
- frontend/src/Chat/components/ChatRoom/BanButton.tsx
- frontend/src/Chat/components/ChatRoom/ChatRoom.tsx
- frontend/src/Chat/components/ChatRoom/MuteButton.tsx
- frontend/src/Chat/components/ChatRoom/UpdateChatRoomModal.tsx
- frontend/src/Chat/components/ChatRoom/UpdateRoomButton.tsx
- frontend/src/Chat/components/ChatRoom/UserListDisplay.tsx
- frontend/src/Chat/components/utils/Modal/ChatRoomSetupModal.tsx
- frontend/src/Chat/components/utils/context.tsx
resolve #170 
試しにコンテキスト使ってみました。
props自体は減りましたが、コード量がそこまで減るわけではなく、、、
> [チャット]context

- backend/src/common/app.module.ts
- backend/src/common/dto/users.dto.ts
- backend/src/entities/users.entity.ts
- backend/src/main.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.module.ts
- backend/src/users/users.service.ts
- frontend/src/User/Resistration.tsx
- frontend/src/types/User.d.ts
- frontend/src/utils/userAxios.tsx
- swagger/api.yml
#164 の続きです
別テーブルにbase64で保存しました。
次のPRではログイン処理を作ります。
#100
> [User] 画像をDBに保存

- backend/src/common/dto/users.dto.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
- frontend/src/User/components/SignIn.tsx
- frontend/src/types/User.d.ts
- frontend/src/utils/userAxios.tsx
- swagger/api.yml
> [User] Sign In

- frontend/src/Chat/components/Chat/Chat.tsx
- frontend/src/Chat/components/Chat/ChatMessageDisplay.tsx
- frontend/src/Chat/components/Chat/ChatMessageSend.tsx
- frontend/src/Chat/components/ChatList/ChatList.tsx
- frontend/src/Chat/components/ChatList/ChatListDisplay.tsx
- frontend/src/Chat/components/ChatList/CreateChatRoomModal.tsx
- frontend/src/Chat/components/ChatList/CreateRoomButton.tsx
- frontend/src/Chat/components/ChatList/EnterButton.tsx
- frontend/src/Chat/components/ChatRoom/AdminButton.tsx
- frontend/src/Chat/components/ChatRoom/ChatRoom.tsx
- frontend/src/Chat/components/ChatRoom/UpdateChatRoomModal.tsx
- frontend/src/Chat/components/ChatRoom/UpdateRoomButton.tsx
- frontend/src/Chat/components/ChatRoom/UserListDisplay.tsx
- frontend/src/Chat/components/utils/Modal/ChatRoomSetupModal.tsx
- frontend/src/Chat/components/utils/userStatusUtils.tsx
- frontend/src/User/components/SignIn.tsx
- frontend/src/types/Chat.d.ts
> [チャット]use global context

- frontend/src/Chat/components/Chat/Chat.tsx
- frontend/src/Chat/components/Chat/ChatMessageDisplay.tsx
- frontend/src/Chat/components/ChatList/EnterButton.tsx
- frontend/src/Chat/components/ChatRoom/ChatRoom.tsx
- frontend/src/types/Chat.d.ts
> [チャット]block message invisible

- frontend/src/App.tsx
- frontend/src/TopPage.tsx
- frontend/src/User/components/SignIn.tsx
- frontend/src/utils/userAxios.tsx
> [Front] login状態保持

- frontend/src/Chat/types/Chat.d.ts
- frontend/src/User/components/Profile/OtherUserProfile.tsx
- frontend/src/User/utils/userStatusUtils.tsx
- frontend/src/utils/Icon/BlockIcon.tsx
- frontend/src/utils/chatBlockUserAxios.tsx
> [Profile]block button

- frontend/src/User/components/Profile/FriendList.tsx
- frontend/src/User/components/Profile/FriendPendingList.tsx
- frontend/src/User/components/Profile/MyPage.tsx
#211 関連
まずは、表示用のtabのみ追加。
この後は各Tabの中を変更するだけなので、素結合に作業を進められる（はず）
> [Profile]add tab

- frontend/src/Chat/components/Chat/ChatModal.tsx
#206 
チャット相手を選択してゲームを開始するためのボタンを配置しました。
ボタンを押しても（今は）何も起こりません。
> [チャット]Game button

- backend/src/chatDMMembers/chatDMMembers.controller.ts
- backend/src/chatDMMembers/chatDMMembers.module.ts
- backend/src/chatDMMembers/chatDMMembers.service.ts
- backend/src/chatDMMembers/index.ts
- backend/src/common/app.module.ts
- backend/src/common/dto/chatDMMembers.dto.ts
- backend/src/entities/chatDMMembers.entity.ts
- swagger/api.yml
> [チャット]DM backend

- backend/src/common/dto/users.dto.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
- frontend/src/User/components/Profile/FriendList.tsx
- frontend/src/User/components/Profile/FriendPendingList.tsx
- frontend/src/types/User.d.ts
- frontend/src/utils/userAxios.tsx
- swagger/api.yml
resolve #212 
resolve #213 
resolve #211
> [Profile]friend pending list

- frontend/src/Chat/components/ChatList/ChatList.tsx
- frontend/src/User/components/Profile/OtherUserProfile.tsx
- frontend/src/types/Chat.d.ts
- frontend/src/utils/chatDMAxios.tsx
- frontend/src/utils/chatRoomAxios.tsx
> [Profile] DM

- backend/migrations/1676466055353-migrations.ts
- frontend/src/Chat/components/Chat/ChatMessageDisplay.tsx
> [チャット]chat avatar

- .github/workflows/codeball-dry-run.yml
- .vscode/cspell.json
resolve #239 
このPRがマージされると、新しいチェックが走ります。
AIがレビューOK/NGを判定して、ラベルに付与してくれるみたいです。
> [インフラ]Codeball.aiの導入

- frontend/src/Chat/components/Chat/ChatModal.tsx
- frontend/src/Header.tsx
- frontend/src/TopPage.tsx
- frontend/src/User/components/Profile/FriendList.tsx
- frontend/src/User/components/Profile/FriendPendingList.tsx
- frontend/src/User/components/Profile/MyPage.tsx
- frontend/src/User/components/Profile/OtherUserProfile.tsx
resolve #238
resolve #235 
resolve #234 
resolve #237 
resolve #236
> [プロフィール]細かい見た目のIssue解消

- backend/src/common/dto/users.dto.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
- frontend/src/User/components/Profile/OtherUserProfile.tsx
- frontend/src/types/User.d.ts
- frontend/src/utils/userAxios.tsx
- swagger/api.yml
> [プロフィール]フレンド削除機能

- frontend/src/Chat/components/Chat/Chat.tsx
- frontend/src/Chat/components/ChatList/AlertElement.tsx
- frontend/src/Chat/components/ChatList/ChatList.tsx
- frontend/src/Chat/components/ChatRoom/ChatRoom.tsx
- frontend/src/TopPage.tsx
- frontend/src/constants.ts
- frontend/src/types/Chat.d.ts
fix #241
local storageに状態を持つ形で、対応しました。
> [チャット][BUG]kickされた後のアラートを消しても、ブラウザリロードするとアラートが再度表示される

- frontend/src/Chat/components/Chat/ChatMessageDisplay.tsx
- frontend/src/Chat/components/Chat/ChatModal.tsx
> [チャット][BUG]kick機能を全ユーザが利用できる。

- backend/src/game/constants.ts
- backend/src/game/logic.ts
- frontend/src/Game/components/Game/Game.tsx
resolve #253 
resolve #256
ball方向をランダムに。
ゲームロビーの簡単なUIを作った。
もし他のデザインにしたい！という時はやってもらってかまいません。
なぜneeds-careful-reviewなのでしょうか😭特に思い当たるところはないです。。
> Feat/253 match UI

- backend/src/common/dto/users.dto.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
- swagger/api.yml
> [プロフィール]名前重複確認用API

- backend/src/chat/chat.gateway.ts
- frontend/src/Chat/components/Chat/Chat.tsx
> [チャット]fix namespace

- frontend/src/User/components/Profile/FriendList.tsx
- frontend/src/User/components/Profile/MyPage.tsx
> [BUG][プロフィール]フレンドリスト更新

- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/twoFactorAuth.controller.ts
- backend/src/common/dto/auth.dto.ts
- frontend/src/Auth/components/TwoFactorRegModal.tsx
- frontend/src/Auth/components/TwoFactorVerifyModal.tsx
- frontend/src/User/components/SignIn.tsx
- frontend/src/types/auth.d.ts
- frontend/src/utils/authAxios.tsx
resolve #275 
2faとjwt authを繋げました。2faの機能が有効になります。
2faをenable, disableした時にtoastifyで通知が来るようにしました。
> Feat/275 2FA after login

- frontend/src/Chat/components/Chat/ChatMessageDisplay.tsx
Close #286 
ユーザーは、再度招待を送信する前に、少なくとも1分間待たなければなりません。少し待つように警告が表示されます
> fix/ #286 set cooldown time for invite

- cypress/cypress/e2e/game/match.cy.js
- cypress/cypress/e2e/game/matchlist.cy.js
- frontend/src/Game/components/Game/Game.tsx
- frontend/src/Game/components/Game/Player.tsx
- frontend/src/TopPage.tsx
Close #258
サインアウトとサインインを行うことで、ゲームを始められました。
ゲームの終わりまで粘るのではなく、ゲームが始まれるを確認してます。
> simple cypress tests for game

- frontend/src/TopPage.tsx
fix #299 
あまりきれいな見た目じゃないですが。。。
> [TopPage]全てのユーザプロフィールへのリンクを用意する。

- config/.env_docker
> rm env_docker

- backend/src/common/dto/users.dto.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
- frontend/src/User/components/Profile/MyPage.tsx
- frontend/src/utils/userAxios.tsx
- swagger/api.yml
> [プロフィール]edit my profile

- backend/src/chatRoom/chatRoom.service.ts
- backend/src/match/match.service.ts
- backend/src/users/users.service.ts
resolve #308 
dbのfindOneでnullにaccessしそうな部分をexecption handlingしました。
もしかしたら見逃している部分があるかもしれません。
> fix / exception handling

- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/types/auth.d.ts
- frontend/src/Auth/auth.ts
API Responseの型が`any`なので使いそうな部分を定義しました。
> 42API Responseの型を定義

- backend/migrations/1676466055353-migrations.ts
レビューの準備のため、削除しています。matchlistは空であるべきだと思います。
> remove migrations for matchlist

- frontend/src/Game/components/MatchList/MatchList.tsx
ちょっと前にcenterColのスタイルを消したかもしれません。
そこで、bootstrapクラスでセンタリングするようにしました。
> fix matchlist centering

- frontend/src/Game/components/Game/Player.tsx
私のイントラのプロフィール名が7文字では収まらなかったので、少し増やしましたww
> game username display length
